fix: update user_id and party_id being attributes and not methods
NillionNetwork/nillion-docs pull request #19
Opened 2024-04-04 18:42 UTC by Jmgr

This PR updates user_id and party_id being attributes and not methods (updated in https://github.com/NillionNetwork/nillion/pull/1430)

2024-04-05 05:35 UTC, jwolski2 requested changes
Changes lgtm. But "requesting changes" to put a hold on merging it until we are ready for the next public release of the SDK.

2024-04-05 06:42 UTC, lumasepa approved these changes

2024-04-12 18:33 UTC, oceans404 requested changes

2024-04-12 18:33 UTC, oceans404 commented on docs/python-client-reference.md
the python change has not yet been made to make user_id and party_id attributes rather than methods has not yet been merged to main. the python client reference changes should live in a separate branch to go in with the next release

2024-04-12 18:34 UTC, oceans404 commented
@Jmgr could you revise this PR to only include the js changes?

the python changes should go in a release branch

2024-04-16 09:35 UTC, Jmgr commented
> @Jmgr could you revise this PR to only include the js changes?
> 
> the python changes should go in a release branch

Done, but I've put the JS changes in https://github.com/NillionNetwork/nillion-docs/pull/21 and kept the Python ones here.

2024-04-30 22:11 UTC, oceans404 commented
@Jmgr can you update the merge target to the release branch?

2024-05-03 17:26 UTC, merged