add intro video to HH docs
NillionNetwork/nillion-docs pull request #62
Opened 2024-07-09 17:51 UTC by Davetbutler

Small PR to add intro video to HH Goa pages. Want to learn whether this helps with conversion

2024-07-09 18:10 UTC, oceans404 requested changes

2024-07-09 18:10 UTC, oceans404 commented on docs/hacker-house-goa-windows.md
> +<IframeVideo videoSrc="https://www.loom.com/share/c6b7c57f167b44ffb110f552e1c8c943?sid=2d3aaa9a-b5cd-4262-84ee-9f4d743c7283"/>
you need to import IframeVideo

```
import IframeVideo from '@site/src/components/IframeVideo/index';
```

2024-07-09 18:12 UTC, oceans404 approved these changes

2024-07-13 08:05 UTC, Davetbutler commented
Removed video as issues with it being rendered and need to reinstate the colab quickly - so merging this PR now

2024-07-13 08:10 UTC, merged